{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 66,
   "metadata": {},
   "outputs": [],
   "source": [
    "import tensorflow as tf\n",
    "import tensorflow_gnn as tfgnn\n",
    "from matplotlib import pyplot as plt\n",
    "import numpy as np\n",
    "from importlib import reload\n",
    "from sys import modules\n",
    "from schema import TYPE_SPEC\n",
    "from generators import load_dataset_from_data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 67,
   "metadata": {},
   "outputs": [],
   "source": [
    "reload(modules[\"schema\"])\n",
    "from schema import TYPE_SPEC\n",
    "spec = TYPE_SPEC[\"mnist_graph\"]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 68,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Model: \"gnn\"\n",
      "_________________________________________________________________\n",
      " Layer (type)                Output Shape              Param #   \n",
      "=================================================================\n",
      " input_7 (InputLayer)        [()]                      0         \n",
      "                                                                 \n",
      " graph_update_7 (GraphUpdate  ()                       259264    \n",
      " )                                                               \n",
      "                                                                 \n",
      " readout_6 (Readout)         (None, 64)                0         \n",
      "                                                                 \n",
      " dense_6 (Dense)             (None, 10)                650       \n",
      "                                                                 \n",
      "=================================================================\n",
      "Total params: 259,914\n",
      "Trainable params: 259,914\n",
      "Non-trainable params: 0\n",
      "_________________________________________________________________\n"
     ]
    }
   ],
   "source": [
    "input = tf.keras.layers.Input(type_spec=spec)\n",
    "gnn = tfgnn.keras.ConvGNNBuilder(\n",
    "    lambda edge: tfgnn.keras.layers.SimpleConvolution(\n",
    "        tf.keras.layers.Dense(128)\n",
    "    ),\n",
    "    lambda node: tfgnn.keras.layers.NextStateFromConcat(\n",
    "        tf.keras.layers.Dense(64),\n",
    "    ),\n",
    "    )\n",
    "hidden = gnn.Convolve()(input)\n",
    "hidden = tfgnn.keras.layers.Readout(node_set_name=\"pixel\")(hidden)\n",
    "output = tf.keras.layers.Dense(10, activation=\"softmax\")(hidden)\n",
    "\n",
    "model = tf.keras.Model(input, output, name = \"gnn\")\n",
    "model.summary()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 69,
   "metadata": {},
   "outputs": [],
   "source": [
    "model.compile(optimizer=\"adam\", loss=tf.keras.losses.categorical_crossentropy, metrics=[\"accuracy\"])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 73,
   "metadata": {},
   "outputs": [],
   "source": [
    "reload(modules[\"generators\"])\n",
    "from generators import load_dataset_from_data\n",
    "\n",
    "(trn_img, trn_lbl), _ = tf.keras.datasets.mnist.load_data()\n",
    "trn_img = trn_img/255\n",
    "trn_graph = load_dataset_from_data(trn_img, trn_lbl, 32, spec)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 91,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2022-03-02 11:32:02.785307: W tensorflow/core/kernels/data/cache_dataset_ops.cc:768] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.\n"
     ]
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAPsAAAD4CAYAAAAq5pAIAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjUuMSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/YYfK9AAAACXBIWXMAAAsTAAALEwEAmpwYAAAODklEQVR4nO3df6zddX3H8deLcttC+VmZtZY6EJlYySx4A2wwhyMY6IwXkg3toiJj1ixgwDAiYUtkyTabbcIIwY46flSGGCMwmDQKdiQEIYwLVmhBKCKVduUW7BbK0Etb3vvjfnFXuOdzbs/3e36U9/OR3Jxzvu/zPd93v72v+z3nfL7nfBwRAvDWt1e/GwDQG4QdSIKwA0kQdiAJwg4ksXcvNzbTs2K25vRyk0Aqv9T/6tUY91S1WmG3fZqkKyXNkPQvEbG8dP/ZmqPjfUqdTQIoeDDWtKx1/DTe9gxJV0s6XdIiSUttL+r08QB0V53X7MdJejoinomIVyV9U9JIM20BaFqdsC+Q9Nyk25uqZb/G9jLbo7ZHd2i8xuYA1NH1d+MjYmVEDEfE8JBmdXtzAFqoE/bNkhZOun1otQzAAKoT9ockHWn7cNszJX1C0h3NtAWgaR0PvUXETtvnS/qeJoberouI9Y11BqBRtcbZI2K1pNUN9QKgizhdFkiCsANJEHYgCcIOJEHYgSQIO5AEYQeSIOxAEoQdSIKwA0kQdiAJwg4kQdiBJAg7kARhB5Ig7EAShB1IgrADSRB2IAnCDiRB2IEkCDuQBGEHkiDsQBKEHUiCsANJEHYgCcIOJEHYgSRqzeKKt4ATfrtY/ukFLtbfPe/FYv27R93Zsvbh9SPFdTc/9M5ivZ33XPmTlrVdY1trPfaeqFbYbT8rabukXZJ2RsRwE00BaF4TR/YPR0T5zzuAvuM1O5BE3bCHpLtsP2x72VR3sL3M9qjt0R0ar7k5AJ2q+zT+pIjYbPvtku62/eOIuHfyHSJipaSVknSA50bN7QHoUK0je0Rsri63SrpN0nFNNAWgeR2H3fYc2/u/fl3SRySta6oxAM2q8zR+nqTbbL/+ON+IiO820hV65qk/m1muf+iaWo+/o/DC7a5Ft5ZXXlRr01q/dGfL2iev+UJx3QXL76+38QHUcdgj4hlJH2iwFwBdxNAbkARhB5Ig7EAShB1IgrADSfAR1+RWnHxjVx//r19Y3LL2wIuHd3Xb1//WN1rWjh0pnxIytrzpbvqPIzuQBGEHkiDsQBKEHUiCsANJEHYgCcIOJME4O2q5/qWFxfoPRw5rWdt7489qbXvvw95VrD/+/be1rH1x/veK6/7JFy4q1g/9drn3nc9tKtb7gSM7kARhB5Ig7EAShB1IgrADSRB2IAnCDiTBODtq2fzqwcX6zo3PdfzYe79jXrH+5HkLivVT9nmlUC1/hfboX1xVrP/eqR8v1g9cUiz3BUd2IAnCDiRB2IEkCDuQBGEHkiDsQBKEHUiCcXbU8ocHrC3W7xk5r2Vt//8sfyZ80Z1jxfq/zVtdrNexI3YV6+N3vr3NIzzdXDMNaXtkt32d7a22101aNtf23bY3VJflMysA9N10nsbfIOm0Nyy7RNKaiDhS0prqNoAB1jbsEXGvpG1vWDwiaVV1fZWkM5ptC0DTOn3NPi8itlTXn5fU8iRm28skLZOk2dq3w80BqKv2u/EREZKiUF8ZEcMRMTykWXU3B6BDnYZ9zPZ8SaoutzbXEoBu6DTsd0g6u7p+tqTbm2kHQLe0fc1u+2ZJJ0s6xPYmSV+StFzSt2yfK2mjpLO62SQG1zEzy8eLNV9d0aNOds8tLx9SrP/N9UuL9QVX399kOz3RNuwR0epffUrDvQDoIk6XBZIg7EAShB1IgrADSRB2IAk+4oo91j/8fFGx/oORo1rWdv3X88V1F4zveUNr7XBkB5Ig7EAShB1IgrADSRB2IAnCDiRB2IEkGGd/i/Pw0cX6O2Y82OYRuvcr0u7rmk+4/MJi/dCbyl/XvGts4+629JbGkR1IgrADSRB2IAnCDiRB2IEkCDuQBGEHkmCcfQ/goZnF+vYzj21Zu/hv/7W47vtn1vsV+OnOXxbrn1z3mZa1A788p7ju/PvKnykvj9LjjTiyA0kQdiAJwg4kQdiBJAg7kARhB5Ig7EASjLMPgL2Obv395pL05J8fWK6fcXWT7eyWM//54mL90C+/9b5/fU/V9shu+zrbW22vm7TsMtubba+tfpZ0t00AdU3nafwNkk6bYvkVEbG4+lndbFsAmtY27BFxr6RtPegFQBfVeYPufNuPVk/zD251J9vLbI/aHt2h8RqbA1BHp2FfIekISYslbZH0lVZ3jIiVETEcEcNDmtXh5gDU1VHYI2IsInZFxGuSvibpuGbbAtC0jsJue/6km2dKWtfqvgAGQ9txdts3SzpZ0iG2N0n6kqSTbS+WFJKelfS57rW459v5Bx8s1i+45uZi/fR9tzfZTqMOeppPle8p2oY9IpZOsfjaLvQCoIs4XRZIgrADSRB2IAnCDiRB2IEk+IhrA177/WOK9YtXlr/O+ZR9Xqm1/fHY0bK2ZP1Ugyn/b83R3661bew5OLIDSRB2IAnCDiRB2IEkCDuQBGEHkiDsQBKMszfgY1/9j2K97jj6R388Uqz/4qp3tqy98IE2/8VHd9IR9kQc2YEkCDuQBGEHkiDsQBKEHUiCsANJEHYgCcbZp2ns87/bsnbugf9UXPfSseOL9fWntpw9S5Lkl18o1vcZ39S69qfvLa6LPDiyA0kQdiAJwg4kQdiBJAg7kARhB5Ig7EASjLNXPFz+YPeln7+pZW3IM4rrjr9W3s27fr6tWK9jzTHXt7nHrGL1gfHyv23fLeO72RH6pe2R3fZC2/fYftz2etsXVMvn2r7b9obqsnxmCIC+ms7T+J2SLoqIRZJOkHSe7UWSLpG0JiKOlLSmug1gQLUNe0RsiYhHquvbJT0haYGkEUmrqrutknRGl3oE0IDdes1u+zBJx0h6UNK8iNhSlZ6XNK/FOsskLZOk2dq340YB1DPtd+Nt7yfpFkkXRsRLk2sREZJiqvUiYmVEDEfE8FCbN4MAdM+0wm57SBNBvykibq0Wj9meX9XnS9ranRYBNKHt03jblnStpCci4vJJpTsknS1peXV5e1c67JFX584u1k+YvblQ3ae47up7hov1I/RAse4Pvr9Yf+qc/VrW9t3roeK67Zxz/znF+nvu+2Gtx0fvTOc1+4mSPiXpMdtrq2WXaiLk37J9rqSNks7qSocAGtE27BFxnyS3KJ/SbDsAuoXTZYEkCDuQBGEHkiDsQBKEHUiCj7hWNp08VKzPn1EeSy+59Y+vKNYvPvaPivXPLvz3Yv1jc/67UC3/PT9nY3lA5b0X/qxY31WsYpBwZAeSIOxAEoQdSIKwA0kQdiAJwg4kQdiBJBhnrxz2nVeK9R98vPU4/ImzdxTXfd9QeQz/O0d176sAxnb9oljfsOJ9xfpBL5Y/a489B0d2IAnCDiRB2IEkCDuQBGEHkiDsQBKEHUiCcfaK7/9Rsf53n/50y9pf3XhDcd3fmdXdT32fueGjLWv/c9W7iusedAvj6FlwZAeSIOxAEoQdSIKwA0kQdiAJwg4kQdiBJBwR5TvYCyV9XdI8SSFpZURcafsySZ+V9EJ110sjYnXpsQ7w3DjeTPwKdMuDsUYvxbYpZ12ezkk1OyVdFBGP2N5f0sO2765qV0TEPzbVKIDumc787Fskbamub7f9hKQF3W4MQLN26zW77cMkHSPpwWrR+bYftX2d7YNbrLPM9qjt0R0ar9ctgI5NO+y295N0i6QLI+IlSSskHSFpsSaO/F+Zar2IWBkRwxExPKRZ9TsG0JFphd32kCaCflNE3CpJETEWEbsi4jVJX5N0XPfaBFBX27DbtqRrJT0REZdPWj5/0t3OlLSu+fYANGU678afKOlTkh6zvbZadqmkpbYXa2I47llJn+tCfwAaMp134++TNNW4XXFMHcBg4Qw6IAnCDiRB2IEkCDuQBGEHkiDsQBKEHUiCsANJEHYgCcIOJEHYgSQIO5AEYQeSIOxAEm2/SrrRjdkvSNo4adEhkl7sWQO7Z1B7G9S+JHrrVJO9/WZE/MZUhZ6G/U0bt0cjYrhvDRQMam+D2pdEb53qVW88jQeSIOxAEv0O+8o+b79kUHsb1L4keutUT3rr62t2AL3T7yM7gB4h7EASfQm77dNsP2n7aduX9KOHVmw/a/sx22ttj/a5l+tsb7W9btKyubbvtr2hupxyjr0+9XaZ7c3Vvltre0mfelto+x7bj9teb/uCanlf912hr57st56/Zrc9Q9JTkk6VtEnSQ5KWRsTjPW2kBdvPShqOiL6fgGH7Q5JelvT1iDi6Wvb3krZFxPLqD+XBEfHFAentMkkv93sa72q2ovmTpxmXdIakz6iP+67Q11nqwX7rx5H9OElPR8QzEfGqpG9KGulDHwMvIu6VtO0Ni0ckraqur9LEL0vPtehtIETEloh4pLq+XdLr04z3dd8V+uqJfoR9gaTnJt3epMGa7z0k3WX7YdvL+t3MFOZFxJbq+vOS5vWzmSm0nca7l94wzfjA7LtOpj+vizfo3uykiDhW0umSzquerg6kmHgNNkhjp9OaxrtXpphm/Ff6ue86nf68rn6EfbOkhZNuH1otGwgRsbm63CrpNg3eVNRjr8+gW11u7XM/vzJI03hPNc24BmDf9XP6836E/SFJR9o+3PZMSZ+QdEcf+ngT23OqN05ke46kj2jwpqK+Q9LZ1fWzJd3ex15+zaBM491qmnH1ed/1ffrziOj5j6QlmnhH/ieS/rIfPbTo692SflT9rO93b5Ju1sTTuh2aeG/jXElvk7RG0gZJ35c0d4B6u1HSY5Ie1USw5vept5M08RT9UUlrq58l/d53hb56st84XRZIgjfogCQIO5AEYQeSIOxAEoQdSIKwA0kQdiCJ/wOofhTkr0K4kQAAAABJRU5ErkJggg==",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "tf.Tensor(8, shape=(), dtype=int64)\n"
     ]
    }
   ],
   "source": [
    "batch_index = 31\n",
    "data = list(trn_graph.take(1))[0]\n",
    "plt.imshow(np.array(tfgnn.graph_tensor_to_values(data[0])[\"node_sets\"][\"pixel\"][\"hidden_state\"][batch_index]).reshape((28, 28)))\n",
    "plt.show()\n",
    "print(data[1][batch_index])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 72,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/10\n"
     ]
    },
    {
     "ename": "ValueError",
     "evalue": "in user code:\n\n    File \"/home/thomas/Documents/tfgnn-mnist/env/lib/python3.9/site-packages/keras/engine/training.py\", line 1021, in train_function  *\n        return step_function(self, iterator)\n    File \"/home/thomas/Documents/tfgnn-mnist/env/lib/python3.9/site-packages/keras/engine/training.py\", line 1010, in step_function  **\n        outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"/home/thomas/Documents/tfgnn-mnist/env/lib/python3.9/site-packages/keras/engine/training.py\", line 1000, in run_step  **\n        outputs = model.train_step(data)\n    File \"/home/thomas/Documents/tfgnn-mnist/env/lib/python3.9/site-packages/keras/engine/training.py\", line 860, in train_step\n        loss = self.compute_loss(x, y, y_pred, sample_weight)\n    File \"/home/thomas/Documents/tfgnn-mnist/env/lib/python3.9/site-packages/keras/engine/training.py\", line 918, in compute_loss\n        return self.compiled_loss(\n    File \"/home/thomas/Documents/tfgnn-mnist/env/lib/python3.9/site-packages/keras/engine/compile_utils.py\", line 201, in __call__\n        loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n    File \"/home/thomas/Documents/tfgnn-mnist/env/lib/python3.9/site-packages/keras/losses.py\", line 141, in __call__\n        losses = call_fn(y_true, y_pred)\n    File \"/home/thomas/Documents/tfgnn-mnist/env/lib/python3.9/site-packages/keras/losses.py\", line 245, in call  **\n        return ag_fn(y_true, y_pred, **self._fn_kwargs)\n    File \"/home/thomas/Documents/tfgnn-mnist/env/lib/python3.9/site-packages/keras/losses.py\", line 1789, in categorical_crossentropy\n        return backend.categorical_crossentropy(\n    File \"/home/thomas/Documents/tfgnn-mnist/env/lib/python3.9/site-packages/keras/backend.py\", line 5083, in categorical_crossentropy\n        target.shape.assert_is_compatible_with(output.shape)\n\n    ValueError: Shapes (1, 1) and (None, 10) are incompatible\n",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "\u001b[1;32m/home/thomas/Documents/tfgnn-mnist/Main.ipynb Cell 7'\u001b[0m in \u001b[0;36m<cell line: 1>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> <a href='vscode-notebook-cell:/home/thomas/Documents/tfgnn-mnist/Main.ipynb#ch0000006?line=0'>1</a>\u001b[0m model\u001b[39m.\u001b[39;49mfit(trn_graph, epochs\u001b[39m=\u001b[39;49m\u001b[39m10\u001b[39;49m)\n",
      "File \u001b[0;32m~/Documents/tfgnn-mnist/env/lib/python3.9/site-packages/keras/utils/traceback_utils.py:67\u001b[0m, in \u001b[0;36mfilter_traceback.<locals>.error_handler\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m     <a href='file:///~/Documents/tfgnn-mnist/env/lib/python3.9/site-packages/keras/utils/traceback_utils.py?line=64'>65</a>\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mException\u001b[39;00m \u001b[39mas\u001b[39;00m e:  \u001b[39m# pylint: disable=broad-except\u001b[39;00m\n\u001b[1;32m     <a href='file:///~/Documents/tfgnn-mnist/env/lib/python3.9/site-packages/keras/utils/traceback_utils.py?line=65'>66</a>\u001b[0m   filtered_tb \u001b[39m=\u001b[39m _process_traceback_frames(e\u001b[39m.\u001b[39m__traceback__)\n\u001b[0;32m---> <a href='file:///~/Documents/tfgnn-mnist/env/lib/python3.9/site-packages/keras/utils/traceback_utils.py?line=66'>67</a>\u001b[0m   \u001b[39mraise\u001b[39;00m e\u001b[39m.\u001b[39mwith_traceback(filtered_tb) \u001b[39mfrom\u001b[39;00m \u001b[39mNone\u001b[39m\n\u001b[1;32m     <a href='file:///~/Documents/tfgnn-mnist/env/lib/python3.9/site-packages/keras/utils/traceback_utils.py?line=67'>68</a>\u001b[0m \u001b[39mfinally\u001b[39;00m:\n\u001b[1;32m     <a href='file:///~/Documents/tfgnn-mnist/env/lib/python3.9/site-packages/keras/utils/traceback_utils.py?line=68'>69</a>\u001b[0m   \u001b[39mdel\u001b[39;00m filtered_tb\n",
      "File \u001b[0;32m~/Documents/tfgnn-mnist/env/lib/python3.9/site-packages/tensorflow/python/framework/func_graph.py:1147\u001b[0m, in \u001b[0;36mfunc_graph_from_py_func.<locals>.autograph_handler\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m   <a href='file:///~/Documents/tfgnn-mnist/env/lib/python3.9/site-packages/tensorflow/python/framework/func_graph.py?line=1144'>1145</a>\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mException\u001b[39;00m \u001b[39mas\u001b[39;00m e:  \u001b[39m# pylint:disable=broad-except\u001b[39;00m\n\u001b[1;32m   <a href='file:///~/Documents/tfgnn-mnist/env/lib/python3.9/site-packages/tensorflow/python/framework/func_graph.py?line=1145'>1146</a>\u001b[0m   \u001b[39mif\u001b[39;00m \u001b[39mhasattr\u001b[39m(e, \u001b[39m\"\u001b[39m\u001b[39mag_error_metadata\u001b[39m\u001b[39m\"\u001b[39m):\n\u001b[0;32m-> <a href='file:///~/Documents/tfgnn-mnist/env/lib/python3.9/site-packages/tensorflow/python/framework/func_graph.py?line=1146'>1147</a>\u001b[0m     \u001b[39mraise\u001b[39;00m e\u001b[39m.\u001b[39mag_error_metadata\u001b[39m.\u001b[39mto_exception(e)\n\u001b[1;32m   <a href='file:///~/Documents/tfgnn-mnist/env/lib/python3.9/site-packages/tensorflow/python/framework/func_graph.py?line=1147'>1148</a>\u001b[0m   \u001b[39melse\u001b[39;00m:\n\u001b[1;32m   <a href='file:///~/Documents/tfgnn-mnist/env/lib/python3.9/site-packages/tensorflow/python/framework/func_graph.py?line=1148'>1149</a>\u001b[0m     \u001b[39mraise\u001b[39;00m\n",
      "\u001b[0;31mValueError\u001b[0m: in user code:\n\n    File \"/home/thomas/Documents/tfgnn-mnist/env/lib/python3.9/site-packages/keras/engine/training.py\", line 1021, in train_function  *\n        return step_function(self, iterator)\n    File \"/home/thomas/Documents/tfgnn-mnist/env/lib/python3.9/site-packages/keras/engine/training.py\", line 1010, in step_function  **\n        outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"/home/thomas/Documents/tfgnn-mnist/env/lib/python3.9/site-packages/keras/engine/training.py\", line 1000, in run_step  **\n        outputs = model.train_step(data)\n    File \"/home/thomas/Documents/tfgnn-mnist/env/lib/python3.9/site-packages/keras/engine/training.py\", line 860, in train_step\n        loss = self.compute_loss(x, y, y_pred, sample_weight)\n    File \"/home/thomas/Documents/tfgnn-mnist/env/lib/python3.9/site-packages/keras/engine/training.py\", line 918, in compute_loss\n        return self.compiled_loss(\n    File \"/home/thomas/Documents/tfgnn-mnist/env/lib/python3.9/site-packages/keras/engine/compile_utils.py\", line 201, in __call__\n        loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n    File \"/home/thomas/Documents/tfgnn-mnist/env/lib/python3.9/site-packages/keras/losses.py\", line 141, in __call__\n        losses = call_fn(y_true, y_pred)\n    File \"/home/thomas/Documents/tfgnn-mnist/env/lib/python3.9/site-packages/keras/losses.py\", line 245, in call  **\n        return ag_fn(y_true, y_pred, **self._fn_kwargs)\n    File \"/home/thomas/Documents/tfgnn-mnist/env/lib/python3.9/site-packages/keras/losses.py\", line 1789, in categorical_crossentropy\n        return backend.categorical_crossentropy(\n    File \"/home/thomas/Documents/tfgnn-mnist/env/lib/python3.9/site-packages/keras/backend.py\", line 5083, in categorical_crossentropy\n        target.shape.assert_is_compatible_with(output.shape)\n\n    ValueError: Shapes (1, 1) and (None, 10) are incompatible\n"
     ]
    }
   ],
   "source": [
    "model.fit(trn_graph, epochs=10)"
   ]
  }
 ],
 "metadata": {
  "interpreter": {
   "hash": "d6cc1b48ae16f10eafcfc5d9834160e52b9d26f3378f7461b2bc28961673c20a"
  },
  "kernelspec": {
   "display_name": "Python 3.9.10 ('env': venv)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.10"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
